name: Deploy Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle (skip tests)
        run: ./gradlew bootJar -x test

      - name: Verify build output
        run: ls -la build/libs

      - name: Copy JAR file via rsync
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ls build/libs/*.jar  # JAR 파일이 올바르게 생성되었는지 확인
          rsync -avz -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa" build/libs/app.jar ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/app.jar

      - name: Move JAR file and run Docker Compose
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            sudo mv /home/ec2-user/app.jar /var/myapp/app.jar
            cd /home/ec2-user/commerce  # 실제 Docker Compose 설정 파일이 있는 디렉토리 경로로 변경
            sudo docker-compose down
            sudo docker-compose build
            sudo docker-compose up -d
          EOF
