name: Deploy Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle (skip tests)
        run: ./gradlew bootJar -x test

      - name: Verify build output
        run: ls -la build/libs

      - name: Build Docker image
        run: docker build -t my-app:latest .

      - name: Push Docker image to ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}
          docker tag my-app:latest ${{ secrets.ECR_REGISTRY }}/my-app:latest
          docker push ${{ secrets.ECR_REGISTRY }}/my-app:latest

      - name: Deploy to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            # Remove the old application JAR file
            sudo systemctl stop myapp.service || true
            sudo rm -f /var/myapp/app.jar
            sudo rm -rf /var/myapp

            # Deploy the new Docker-based application
            cd /home/ec2-user/commerce
            sudo docker-compose down
            sudo docker-compose pull
            sudo docker-compose up -d
          EOF
