name: Deploy Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle (skip tests)
        run: ./gradlew bootJar -x test

      - name: Verify build output
        run: ls -la build/libs

      - name: Copy JAR file via rsync
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ls build/libs/*.jar  # JAR 파일이 올바르게 생성되었는지 확인
          rsync -avz -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa" build/libs/app.jar ec2-user@$EC2_HOST:/home/ec2-user/app.jar

      - name: Deploy and run Docker Compose on EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ec2-user@$EC2_HOST << 'EOF'
            set -e
            if [ -d "/home/ec2-user/commerce" ]; then
              cd /home/ec2-user/commerce
              git pull
            else
              git clone https://github.com/choiseongho1/commerce.git /home/ec2-user/commerce
              cd /home/ec2-user/commerce
            fi

            # 빌드 및 배포
            chmod +x ./gradlew
            ./gradlew bootJar -x test

            # Docker 이미지 로드
            docker load -i /home/ec2-user/commerce-app.tar
            
            echo "Stopping processes on port 8080..."
            sudo fuser -k 8080/tcp || true

            echo "Bringing down Docker Compose..."
            sudo docker-compose down || true

            echo "Removing old containers..."
            sudo docker rm -f $(docker ps -aq) || true

            echo "Removing unused Docker resources..."
            sudo docker system prune -f --volumes || true

            echo "Starting Docker Compose..."
            sudo docker-compose up -d

            echo "Deployment finished."
          EOF
